rss: "/feed.xml"
rss-description: A nice rss feed for you rss fiends.

# theme stuff
# theme: jekyll-theme-persephone
remote_theme: erlzhang/jekyll-theme-persephone

# The followings are settings for displays of your blog.
theme_setting:
  # The ← back URL on the top of your post page. Default is your site's home page.
  blog_page: "docs/index.md"
  # The URL on your name on the bottom of your post and page. Default is your site's home page.
  about_page: "docs/about.md"
  # The nav links on the top right of home/page/post/blog layout. You can set a local page(by setting a layout's path) or and external link ( both title and url are required) here.
  nav_pages:
    - "docs/about.md"